// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Monolith;

#nullable disable

namespace Monolith.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Monolith.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Стеновые материалы"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Кровельные материалы"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Сухие смеси"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Древесные материалы"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Крепеж и метизы"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Инструменты"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Сантехника"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Электрика"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Отделочные материалы"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Утеплители"
                        });
                });

            modelBuilder.Entity("Monolith.Models.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Offers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Кирпич керамический М-150"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Блок газосиликатный 600x300x200"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Пеноблок D600 600x300x200"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Металлочерепица Монтеррей 0.5мм"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Профнастил С-8 2м"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Гибкая черепица Shinglas"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Цемент М500 50кг"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Пескобетон М300 40кг"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Штукатурка гипсовая 30кг"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Клей для плитки 25кг"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Брус 100x100x6000"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Доска обрезная 50x150x6000"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Фанера ФК 1525x1525x12мм"
                        },
                        new
                        {
                            Id = 14,
                            Name = "ОСБ плита 2500x1250x9мм"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Анкер клиновой 10x100"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Саморезы по дереву 5x50 (упак 200шт)"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Дюбель-гвоздь 6x40 (упак 100шт)"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Болты фундаментные 16x200"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Перфоратор Bosch GBH 2-26"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Шуруповерт Makita 6281D"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Болгарка УШМ 125мм"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Лазерный уровень 3 линии"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Труба ППР 25x4.2 (3м)"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Смеситель для ванны"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Унитаз компакт"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Раковина керамическая 60см"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Кабель ВВГ-нг 3x2.5 (м)"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Автомат IEK 16A"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Розетка с заземлением"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Выключатель одноклавишный"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Обои виниловые 10м"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Краска акриловая 5л"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Плитка керамическая 30x30"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Ламинат 32 класс 8мм"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Минеральная вата Rockwool 50мм"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Пенопласт ПСБ-С 25 1000x1000x50"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Эковата (мешок 15кг)"
                        });
                });

            modelBuilder.Entity("Monolith.Models.Price", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("OfferId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("offer_id");

                    b.Property<int>("RegionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("region_id");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("OfferId");

                    b.HasIndex("RegionId");

                    b.ToTable("Prices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OfferId = 1,
                            RegionId = 1,
                            Value = 65m
                        },
                        new
                        {
                            Id = 2,
                            OfferId = 2,
                            RegionId = 1,
                            Value = 4500m
                        },
                        new
                        {
                            Id = 3,
                            OfferId = 4,
                            RegionId = 1,
                            Value = 650m
                        },
                        new
                        {
                            Id = 4,
                            OfferId = 7,
                            RegionId = 1,
                            Value = 550m
                        },
                        new
                        {
                            Id = 5,
                            OfferId = 11,
                            RegionId = 1,
                            Value = 850m
                        },
                        new
                        {
                            Id = 6,
                            OfferId = 15,
                            RegionId = 1,
                            Value = 45m
                        },
                        new
                        {
                            Id = 7,
                            OfferId = 19,
                            RegionId = 1,
                            Value = 8900m
                        },
                        new
                        {
                            Id = 8,
                            OfferId = 23,
                            RegionId = 1,
                            Value = 350m
                        },
                        new
                        {
                            Id = 9,
                            OfferId = 27,
                            RegionId = 1,
                            Value = 85m
                        },
                        new
                        {
                            Id = 10,
                            OfferId = 31,
                            RegionId = 1,
                            Value = 1200m
                        },
                        new
                        {
                            Id = 11,
                            OfferId = 1,
                            RegionId = 2,
                            Value = 62m
                        },
                        new
                        {
                            Id = 12,
                            OfferId = 2,
                            RegionId = 2,
                            Value = 4300m
                        },
                        new
                        {
                            Id = 13,
                            OfferId = 4,
                            RegionId = 2,
                            Value = 620m
                        },
                        new
                        {
                            Id = 14,
                            OfferId = 7,
                            RegionId = 2,
                            Value = 530m
                        },
                        new
                        {
                            Id = 15,
                            OfferId = 11,
                            RegionId = 2,
                            Value = 820m
                        },
                        new
                        {
                            Id = 16,
                            OfferId = 19,
                            RegionId = 2,
                            Value = 8700m
                        },
                        new
                        {
                            Id = 17,
                            OfferId = 27,
                            RegionId = 2,
                            Value = 82m
                        },
                        new
                        {
                            Id = 18,
                            OfferId = 1,
                            RegionId = 3,
                            Value = 60m
                        },
                        new
                        {
                            Id = 19,
                            OfferId = 2,
                            RegionId = 3,
                            Value = 4200m
                        },
                        new
                        {
                            Id = 20,
                            OfferId = 4,
                            RegionId = 3,
                            Value = 600m
                        },
                        new
                        {
                            Id = 21,
                            OfferId = 7,
                            RegionId = 3,
                            Value = 520m
                        },
                        new
                        {
                            Id = 22,
                            OfferId = 11,
                            RegionId = 3,
                            Value = 800m
                        },
                        new
                        {
                            Id = 23,
                            OfferId = 19,
                            RegionId = 3,
                            Value = 8500m
                        },
                        new
                        {
                            Id = 24,
                            OfferId = 23,
                            RegionId = 3,
                            Value = 330m
                        },
                        new
                        {
                            Id = 25,
                            OfferId = 27,
                            RegionId = 3,
                            Value = 80m
                        },
                        new
                        {
                            Id = 26,
                            OfferId = 1,
                            RegionId = 4,
                            Value = 63m
                        },
                        new
                        {
                            Id = 27,
                            OfferId = 2,
                            RegionId = 4,
                            Value = 4400m
                        },
                        new
                        {
                            Id = 28,
                            OfferId = 4,
                            RegionId = 4,
                            Value = 630m
                        },
                        new
                        {
                            Id = 29,
                            OfferId = 7,
                            RegionId = 4,
                            Value = 540m
                        },
                        new
                        {
                            Id = 30,
                            OfferId = 11,
                            RegionId = 4,
                            Value = 830m
                        },
                        new
                        {
                            Id = 31,
                            OfferId = 19,
                            RegionId = 4,
                            Value = 8800m
                        },
                        new
                        {
                            Id = 32,
                            OfferId = 27,
                            RegionId = 4,
                            Value = 83m
                        },
                        new
                        {
                            Id = 33,
                            OfferId = 1,
                            RegionId = 5,
                            Value = 61m
                        },
                        new
                        {
                            Id = 34,
                            OfferId = 2,
                            RegionId = 5,
                            Value = 4250m
                        },
                        new
                        {
                            Id = 35,
                            OfferId = 4,
                            RegionId = 5,
                            Value = 610m
                        },
                        new
                        {
                            Id = 36,
                            OfferId = 7,
                            RegionId = 5,
                            Value = 525m
                        },
                        new
                        {
                            Id = 37,
                            OfferId = 11,
                            RegionId = 5,
                            Value = 810m
                        },
                        new
                        {
                            Id = 38,
                            OfferId = 19,
                            RegionId = 5,
                            Value = 8600m
                        },
                        new
                        {
                            Id = 39,
                            OfferId = 23,
                            RegionId = 5,
                            Value = 340m
                        },
                        new
                        {
                            Id = 40,
                            OfferId = 27,
                            RegionId = 5,
                            Value = 81m
                        });
                });

            modelBuilder.Entity("Monolith.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("region_name");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RegionName = "Москва"
                        },
                        new
                        {
                            Id = 2,
                            RegionName = "Санкт-Петербург"
                        },
                        new
                        {
                            Id = 3,
                            RegionName = "Екатеринбург"
                        },
                        new
                        {
                            Id = 4,
                            RegionName = "Казань"
                        },
                        new
                        {
                            Id = 5,
                            RegionName = "Новосибирск"
                        });
                });

            modelBuilder.Entity("offer_categories", b =>
                {
                    b.Property<int>("OfferId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OfferId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("offer_categories", (string)null);

                    b.HasData(
                        new
                        {
                            OfferId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            OfferId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            OfferId = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            OfferId = 4,
                            CategoryId = 2
                        },
                        new
                        {
                            OfferId = 5,
                            CategoryId = 2
                        },
                        new
                        {
                            OfferId = 6,
                            CategoryId = 2
                        },
                        new
                        {
                            OfferId = 7,
                            CategoryId = 3
                        },
                        new
                        {
                            OfferId = 8,
                            CategoryId = 3
                        },
                        new
                        {
                            OfferId = 9,
                            CategoryId = 3
                        },
                        new
                        {
                            OfferId = 10,
                            CategoryId = 3
                        },
                        new
                        {
                            OfferId = 11,
                            CategoryId = 4
                        },
                        new
                        {
                            OfferId = 12,
                            CategoryId = 4
                        },
                        new
                        {
                            OfferId = 13,
                            CategoryId = 4
                        },
                        new
                        {
                            OfferId = 14,
                            CategoryId = 4
                        },
                        new
                        {
                            OfferId = 15,
                            CategoryId = 5
                        },
                        new
                        {
                            OfferId = 16,
                            CategoryId = 5
                        },
                        new
                        {
                            OfferId = 17,
                            CategoryId = 5
                        },
                        new
                        {
                            OfferId = 18,
                            CategoryId = 5
                        },
                        new
                        {
                            OfferId = 19,
                            CategoryId = 6
                        },
                        new
                        {
                            OfferId = 20,
                            CategoryId = 6
                        },
                        new
                        {
                            OfferId = 21,
                            CategoryId = 6
                        },
                        new
                        {
                            OfferId = 22,
                            CategoryId = 6
                        },
                        new
                        {
                            OfferId = 23,
                            CategoryId = 7
                        },
                        new
                        {
                            OfferId = 24,
                            CategoryId = 7
                        },
                        new
                        {
                            OfferId = 25,
                            CategoryId = 7
                        },
                        new
                        {
                            OfferId = 26,
                            CategoryId = 7
                        },
                        new
                        {
                            OfferId = 27,
                            CategoryId = 8
                        },
                        new
                        {
                            OfferId = 28,
                            CategoryId = 8
                        },
                        new
                        {
                            OfferId = 29,
                            CategoryId = 8
                        },
                        new
                        {
                            OfferId = 30,
                            CategoryId = 8
                        },
                        new
                        {
                            OfferId = 31,
                            CategoryId = 9
                        },
                        new
                        {
                            OfferId = 32,
                            CategoryId = 9
                        },
                        new
                        {
                            OfferId = 33,
                            CategoryId = 9
                        },
                        new
                        {
                            OfferId = 34,
                            CategoryId = 9
                        },
                        new
                        {
                            OfferId = 35,
                            CategoryId = 10
                        },
                        new
                        {
                            OfferId = 36,
                            CategoryId = 10
                        },
                        new
                        {
                            OfferId = 37,
                            CategoryId = 10
                        });
                });

            modelBuilder.Entity("Monolith.Models.Price", b =>
                {
                    b.HasOne("Monolith.Models.Offer", "Offer")
                        .WithMany("Prices")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Monolith.Models.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offer");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("offer_categories", b =>
                {
                    b.HasOne("Monolith.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Monolith.Models.Offer", null)
                        .WithMany()
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Monolith.Models.Offer", b =>
                {
                    b.Navigation("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
